import puppeteer from 'puppeteer-core';
const [token, tab] = process.argv.slice(2);
const b = await puppeteer.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 900 });
await p.goto('http://127.0.0.1:3100/login');
await p.evaluate((t) => localStorage.setItem('wsender.token', t), token);
p.on('console', (m) => console.log('C:', m.type(), m.text().slice(0, 300)));
p.on('pageerror', (e) => console.log('E:', String(e).slice(0, 400)));
await p.goto(`http://127.0.0.1:3100/school?tab=${tab}`, { waitUntil: 'domcontentloaded' });
await new Promise((r) => setTimeout(r, 3000));
await b.close();
